name: mir-kiosk-neverputt
adopt-info: neverputt
summary: neverputt packaged as a mir-kiosk snap
description: neverputt packaged as a mir-kiosk snap
confinement: strict
grade: stable
base: core22
license: GPL-2.0

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

environment:
  LD_LIBRARY_PATH:           $SNAP/graphics/usr/lib/:$SNAP/graphics/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}:$SNAP/usr/lib/:$SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}:$SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/blas:$SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/lapack${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
  LIBGL_DRIVERS_PATH:        $SNAP/graphics/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri/
  LIBVA_DRIVERS_PATH:        $SNAP/graphics/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri/
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/graphics/usr/share/glvnd/egl_vendor.d

  # Prep SDL
  SDL_VIDEODRIVER: wayland

layout:
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/share/games:
    bind: $SNAP/usr/share/games
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/sounds:
    bind: $SNAP/usr/share/sounds
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  /usr/share/libdrm:  # Needed by mesa-core22-test on AMD GPUs
    bind: $SNAP/graphics/usr/share/libdrm
  /usr/share/drirc.d:  # Used by mesa-core22-test for app specific workarounds
    bind: $SNAP/graphics/usr/share/drirc.d
  /usr/games:
    bind: $SNAP/usr/games
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio:
    bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio

plugs:
  wayland:
  opengl:
  audio-playback:
  hardware-observe: # This allows some UDEV access neverputt wants
  graphics-core22:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core22-test/edge

apps:
  daemon:
    command-chain:
      - bin/run-daemon
      - bin/wayland-launch
    command: usr/games/neverputt
    daemon: simple
    restart-condition: always
    environment:
      # Prep PulseAudio
      PULSE_SYSTEM: 1
      PULSE_RUNTIME_PATH: /var/run/pulse

  mir-kiosk-neverputt:
    command-chain:
      - bin/wayland-launch
    command: usr/games/neverputt
    desktop: usr/share/applications/neverputt.desktop
    environment:
      # Prep PulseAudio
      PULSE_SERVER: unix:$XDG_RUNTIME_DIR/../pulse/native

parts:
  neverputt:
    plugin: nil
    override-pull: |
      craftctl default
      craftctl set version=`LANG=C apt-cache policy neverputt | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/\1/p'`
    override-build: |
      craftctl default
      sed -i s:Icon=neverputt:Icon=/usr/share/games/neverball/icon/neverputt.png:g $SNAPCRAFT_PART_INSTALL/usr/share/applications/neverputt.desktop
    stage-packages:
      - neverputt

  config:
    plugin: dump
    source: config

  mir-kiosk-snap-launch:
    plugin: dump
    source: https://github.com/MirServer/mir-kiosk-snap-launch.git
    override-build:  $SNAPCRAFT_PART_BUILD/build-with-plugs.sh opengl wayland graphics-core22 hardware-observe
    stage-packages:
     - inotify-tools

  sdl2:
    plugin: nil
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsdl2-mixer-2.0-0
      - libsdl2-net-2.0-0

  cleanup:
    after: [neverputt, config, mir-kiosk-snap-launch, sdl2]
    plugin: nil
    build-snaps: [ mesa-core22-test/edge ]
    override-prime: |
      set -eux
      cd /snap/mesa-core22-test/current/usr/
      find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/usr/{} \;
      for CRUFT in bug drirc.d glvnd libdrm lintian man; do
        rm -rf "$SNAPCRAFT_PRIME/usr/share/$CRUFT"
      done
      for CRUFT in alsa doc doc-base locale pkgconfig; do
        rm -rf "$SNAPCRAFT_PRIME/usr/share/$CRUFT"
      done
